### ISSUE TITLE
Tracking having hard time following if two identical object has cross each other

### ISSUE THREAD

**Issue by EwingKang** [intel/ros2_object_analytics#74]
I've written a node that filters the result of tracking based on ID. This node will select object "person" with with smallest ID number and publishes its TF.
https://youtu.be/omBEwIIn3og

During the test, I've noticed that:
a) The object tracking is more stable on the "locked" object (see issue #73). For example, 1:10-ID#243 sustained much longer then other ID.
b) The tracker is having trouble following the object the two of the same object crossed. For example, at video 00:49-ID#243, 1:26-ID#251, and 1:54-ID#251.
The tracker worked pretty well if objects don't cross each other. (1:35-1:55)

Apparently, the object detection only outputs object tags with bounding box, so the OA has no way of telling which one remains the same object. Still, it would have been better if it can tell the difference somehow. Maybe by some kind of  image matching? I think people can accept that the computer is unable to tell the difference between if they all looked similar (i.e 5 guys wearing suits). But in this case, we're having a significant difference in clothing and appearance. 

This is definitely a directly relationship to the person re-ID problem (OpenVINO: https://github.com/intel/ros2_openvino_toolkit/tree/devel). Currently the re-ID in OpenVINO is having trouble recognize the same person. It often keep assigning new ID to the same person by image method. OTOH, this OA seems to assigned the same ID to different person by spatial method. These two method seems pretty complementary, I think the performance would be much greater if somehow we can join these two components.

Great work on the OA and OpenVINO though, they're opening up so much possibilities!

P.s. To mod: Not sure if this counts as issue or not. Feel free to change the status/tag on this one.

**Comment by challenzhou** [comment]
Tracking module has 2 features, single tracking and multi-tracking, while single tracking is aimed to handle local image match, multi-tracking to handle trackers and resolve the issue of occlusions and movements.
Currently single tracking in this project is ready, multi-tracking is a draft framework and still working in progress. That's why you saw single objects tracks well and multiple cross objects tracking has some problem. Please also be noted, there is no perfect solution in industry yet.

If you are trying to use Re-ID for tracking, it would be another story which can be called "track by detect", it can associate detections from different frames, by the performance would be slower than detection, which is not the aim of this project, and also have the same issues on multi-tracking.

If filter "person" in tracking works for your project, you can do the filter between detection module and tracking module or hack in the detection side so that it can save transactions and computations. 

It is good conversation so that we can know the scenarios of you guys take this module into, but it's better not start this as issue. Suggest to start discussion or query from mail or other channels.

**Comment by challen-zhou** [comment]
@EwingKang , do you have some further question? Or i would like to close this issue since multi-tracking is in progress, we can have further discussion then.

**Comment by EwingKang** [comment]
@challen-zhou  I'm good with the closure of the issue. Sounds like you're onto something. I'm looking forward to multi-tracking.
